apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    tekton.dev/displayName: Ansible Runner
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/platforms: linux/amd64
    tekton.dev/tags: cli
  name: ansible-runner
spec:
  description: Task to run Ansible playbooks using Ansible Runner
  params:
  - default: project
    description: The project directory under the workspace runner-dir
    name: project-dir
    type: string
  - default:
    - --help
    description: The arguments to pass ansible-runner
    name: args
    type: array
  - default: /tekton/home
    description: Absolute path to the user's home directory.
    name: user-home
    type: string
  - default: quay.io/ansible/awx-ee:24.3.1
    description: Ansible runner image.
    name: image
    type: string
  stepTemplate:
    computeResources: {}
    env:
    - name: HOME
      value: $(params.user-home)
  steps:
  - computeResources: {}
    image: $(params.image)
    name: requirements
    script: |
      #!/bin/bash
      set -e

      if [ -f requirements.txt ];
      then
        pip3 install --user \
          -r requirements.txt
      fi

      if [ -f  requirements.yml ];
      then
        ansible-galaxy role install -vv \
          -r requirements.yml
        ansible-galaxy collection install -vv \
          -r requirements.yml
      fi
    workingDir: $(workspaces.runner-dir.path)/$(params.project-dir)
  - args:
    - run
    - $(params.args)
    - $(params.project-dir)
    command:
    - /usr/local/bin/ansible-runner
    computeResources: {}
    image: $(params.image)
    name: run-playbook
    securityContext:
      runAsUser: 0
    workingDir: $(workspaces.runner-dir.path)
  workspaces:
  - description: The Ansibler runner directory
    name: runner-dir
