apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    task.kubevirt.io/associatedServiceAccount: wait-for-vmi-status-task
    vmiNamespace.params.task.kubevirt.io/type: namespace
  labels:
    app.kubernetes.io/component: tektonTasks
    app.kubernetes.io/name: tekton-tasks
    task.kubevirt.io/category: wait-for-vmi-status
    task.kubevirt.io/type: wait-for-vmi-status
  name: wait-for-vmi-status
spec:
  params:
  - description: Name of a VirtualMachineInstance to wait for.
    name: vmiName
    type: string
  - default: ""
    description: Namespace of a VirtualMachineInstance to wait for. (defaults to manifest
      namespace or active namespace)
    name: vmiNamespace
    type: string
  - default: ""
    description: A label selector expression to decide if the VirtualMachineInstance
      (VMI) is in a success state. Eg. "status.phase == Succeeded". It is evaluated
      on each VMI update and will result in this task succeeding if true.
    name: successCondition
    type: string
  - default: ""
    description: A label selector expression to decide if the VirtualMachineInstance
      (VMI) is in a failed state. Eg. "status.phase in (Failed, Unknown)". It is evaluated
      on each VMI update and will result in this task failing if true.
    name: failureCondition
    type: string
  steps:
  - command:
    - entrypoint
    computeResources: {}
    env:
    - name: COMMAND
      value: wait-for-vmi-status
    - name: VMI_NAME
      value: $(params.vmiName)
    - name: VMI_NAMESPACE
      value: $(params.vmiNamespace)
    - name: SUCCESS_CONDITION
      value: $(params.successCondition)
    - name: FAILURE_CONDITION
      value: $(params.failureCondition)
    image: registry.redhat.io/container-native-virtualization/kubevirt-tekton-tasks-create-datavolume-rhel9:v4.14
    name: wait-for-vmi-status
