apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: demo-l2-network
  namespace: koray
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  config: |2
    {
            "cniVersion": "0.3.1", 
            "name": "demo-l2-network", 
            "type": "ovn-k8s-cni-overlay", 
            "topology":"layer2", 
            "mtu": 1300, 
            "netAttachDefName": "koray/demo-l2-network" 
    }
