apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "29"
  name: velero-credentials-job
spec:
  template:
    spec:
      containers:
      - name: velero-credentials
        image: alpine/k8s:1.30.0
        command:
        - sh
        - -c
        - |
          OBCNAME=oadp-backups
          ACCESS_KEY=$(kubectl get secret $OBCNAME -o jsonpath='{.data.AWS_ACCESS_KEY_ID}' | base64 -d)
          SECRET_KEY=$(kubectl get secret $OBCNAME -o jsonpath='{.data.AWS_SECRET_ACCESS_KEY}' | base64 -d)

          cat << EOF > /tmp/credentials-velero
          [default]
          aws_access_key_id=${ACCESS_KEY}
          aws_secret_access_key=${SECRET_KEY}
          EOF

          kubectl apply -f - <<EOF
          apiVersion: v1
          kind: Secret
          metadata:
            name: cloud-credentials
          data:
            cloud: $(cat /tmp/credentials-velero | base64 -w0)
          EOF
      restartPolicy: Never
      serviceAccountName: gitops-job
