apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "21"
  name: gitops-job-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitops-job
subjects:
- kind: ServiceAccount
  name: gitops-job
