apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "19"
  name: gitops-job
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "delete", "patch", "get", "list", "watch"]
