apiVersion: velero.io/v1
kind: Backup
metadata:
  name: demo-oadp-backup-1
spec:
  includedNamespaces:
  - demo-oadp-backup-vms
  includedResources:
  - virtualmachines.kubevirt.io
  - virtualmachineinstances.kubevirt.io
  - datavolumes.cdi.kubevirt.io
  - persistentvolumeclaims
  - pods
  snapshotVolumes: true
  storageLocation: demo-oadp-dpa-1
  ttl: 720h0m0s
  defaultVolumesToFsBackup: false
  snapshotMoveData: true
