apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: windows-demo-vm
  namespace: demo-vm-provisioning
  labels:
    app: windows-demo-vm
spec:
  dataVolumeTemplates:
    - metadata:
        name: windows-demo-vm
      spec:
        preallocation: false
        sourceRef:
          kind: DataSource
          name: win2k16
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 32Gi
  runStrategy: RerunOnFailure
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: medium
        vm.kubevirt.io/os: windows2k16
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: windows-demo-vm
        kubevirt.io/size: medium
    spec:
      architecture: amd64
      domain:
        clock:
          timer:
            hpet:
              present: false
            hyperv: {}
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
          utc: {}
        cpu:
          cores: 4
          sockets: 1
          threads: 1
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: rootdisk
            - cdrom:
                bus: sata
              name: windows-drivers-disk
            - cdrom:
                bus: sata
              name: sysprep
          inputs:
            - bus: usb
              name: tablet
              type: tablet
          interfaces:
            - macAddress: '02:a4:1a:00:00:18'
              masquerade: {}
              model: virtio
              name: default
        features:
          acpi: {}
          apic: {}
          hyperv:
            reenlightenment: {}
            ipi: {}
            synic: {}
            synictimer:
              direct: {}
            spinlocks:
              spinlocks: 8191
            reset: {}
            relaxed: {}
            vpindex: {}
            runtime: {}
            tlbflush: {}
            frequencies: {}
            vapic: {}
        machine:
          type: pc-q35-rhel9.2.0
        memory:
          guest: 8Gi
        resources: {}
      evictionStrategy: LiveMigrate
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 3600
      volumes:
        - dataVolume:
            name: windows-demo-vm
          name: rootdisk
        - containerDisk:
            image: 'registry.redhat.io/container-native-virtualization/virtio-win-rhel9@sha256:0c536c7aba76eb9c1e75a8f2dc2bbfa017e90314d55b242599ea41f42ba4434f'
          name: windows-drivers-disk
        - name: sysprep
          sysprep:
            configMap:
              name: sysprep-unattend.xml
