apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "29"
  name: fedora-demo-vm-replication-dest
spec:
  rsyncTLS:
    copyMethod: Snapshot
    destinationPVC: fedora-demo-vm
    keySecret: tls-key-secret-fedora-demo-vm
    serviceType: ClusterIP
    storageClassName: lvms-vg1
    volumeSnapshotClassName: lvms-vg1
