apiVersion: v1
kind: Service
metadata:
  name: volsync-rsync-tls-dst-fedora-demo-vm-replication-dest
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
    argocd.argoproj.io/sync-wave: "59"
    skupper.io/address: fedora-demo-vm-replication-dest
    skupper.io/target: volsync-rsync-tls-dst-fedora-demo-vm-replication-dest
    skupper.io/port: "8000"
    skupper.io/proxy: tcp
