apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "39"
  name: volsync-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: volsync-reader
subjects:
- kind: ServiceAccount
  name: volsync-dst-fedora-demo-vm-replication-dest
  namespace: demo-vm-dr-volsync
