apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "19"
  name: oadp-backups
spec:
  generateBucketName: oadp-backups
  objectBucketName: obc-demo-oadp-backups
  storageClassName: ocs-storagecluster-ceph-rgw