apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: fedora-demo-vm-snapshot
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  volumeSnapshotClassName: lvms-vg1
  source:
    persistentVolumeClaimName: fedora-demo-vm