apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-windows-vmpool
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-windows-vmpool
  project: default
  source:
    repoURL: https://gitea.apps.openshift.demoes.live/demo-user/gitops-demo.git
    path: applications/demo-windows-vmpool/manifests
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: false
  ignoreDifferences:
  - group: "pool.kubevirt.io"
    kind: "VirtualMachinePool"
    jsonPointers:
    - /spec/replicas