apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-dr-volsync
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchExpressions:
          - key: cluster.kubernetes.io/cluster-name
            operator: In
            values:
              - cls1
              - cls2
  template:
    metadata:
      name: '{{.name}}-demo-dr-volsync'
    spec:
      project: default
      source:
        path: 'applicationsets/demo-dr-volsync/manifests/{{.name}}'
        repoURL: https://gitea.apps.openshift.demoes.live/demo-user/gitops-demo.git
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
        - CreateNamespace=true
      destination:
        server: '{{.server}}'
        namespace: demo-vm-dr-volsync