apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: virtualization
  namespace: openshift-gitops
spec:
  generators:
  # Only select external clusters, excludes local cluster
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: "{{nameNormalized}}-virtualization"
    spec:
      project: default
      source:
        repoURL: https://gitea.apps.openshift.demoes.live/demo-user/gitops-demo.git
        targetRevision: HEAD
        path: applicationsets/virtualization/manifests
      destination:
        #server: "{{server}}"
        server: https://kubernetes.default.svc
        namespace: openshift-cnv
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
