apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: discovery.iso
spec:
  source:
    http:
      url: "http://distro.ibiblio.org/tinycorelinux/9.x/x86/release/Core-current.iso"
  pvc:
    volumeMode: Block
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 2Gi