apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: localnet-vlan150
spec:
  config: |
    {
            "cniVersion": "0.3.1", 
            "name": "localnet-vlan150", 
            "type": "ovn-k8s-cni-overlay", 
            "topology": "localnet",
            "vlanID": 150,
            "mtu": 1500,
            "netAttachDefName": "default/localnet-vlan150" 
    }
