apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "80"
  labels:
    app: worker-0
  name: worker-0
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        annotations:
          cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
        creationTimestamp: null
        name: worker-0
      spec:
        source:
          blank: {}
        storage:
          resources:
            requests:
              storage: 120Gi
  running: false
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: rhel9
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: worker-0
        kubevirt.io/size: small
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 8
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
              bootOrder: 1
            - cdrom:
                bus: sata
              name: discovery-iso
              bootOrder: 2
          interfaces:
            - bridge: {}
              model: virtio
              name: default
          networkInterfaceMultiqueue: true
          rng: {}
        machine:
          type: pc-q35-rhel9.2.0
        memory:
          guest: 8Gi
        resources: {}
      networks:
        - multus:
            networkName: localnet-vlan150
          name: default
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: worker-0
          name: rootdisk
        - name: discovery-iso
          persistentVolumeClaim:
            claimName: discovery.iso

