apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-vmpool-linux
  namespace: demo-linux-k8s-networking
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: pool.kubevirt.io/v1alpha1
    kind: VirtualMachinePool
    name: vmpool-linux
  targetCPUUtilizationPercentage: 50
