apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: "VM Provisioning Demo Project"
    openshift.io/display-name: VM Provisioning Demo Project
    argocd.argoproj.io/sync-wave: "1"
  name: demo-vm-provisioning
